apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-etcd-backup
  namespace: etcd-bkp
  labels:
    app.kubernetes.io/name: cronjob-etcd-backup
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: cronjob-etcd-backup
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app.kubernetes.io/name: cronjob-etcd-backup
        spec:
          nodeSelector:
            node-role.kubernetes.io/master: ''
          restartPolicy: Never
          activeDeadlineSeconds: 500
          serviceAccountName: cronjob-etcd-bkp-sa
          hostPID: true
          hostNetwork: true
          enableServiceLinks: true
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
          securityContext: {}
          containers:
            - name: cronjob-etcd-backup
              image: registry.redhat.io/openshift4/ose-cli
              terminationMessagePath: /dev/termination-log
              command:
              - /bin/bash
              - '-c'
              - >-
                echo -e '\n\n---\nCreate etcd backup local to PVC\n' &&
                chroot /host /usr/local/bin/cluster-backup.sh /home/core/backup/$(date "+%F_%H%M%S") &&
                echo -e '\n\n---\nCleanup old backups in PVC\n' &&
                chroot /host find /home/core/backup/ -mindepth 1 -type d -mmin +2 -exec rm -rf {} \;
              securityContext:
                privileged: true
                runAsUser: 0
                capabilities:
                  add:
                    - SYS_CHROOT
              imagePullPolicy: Always
              volumeMounts:
                - name: host
                  mountPath: /host
                # Mount PVC for etcd backups
                - name: etcd-backup-volume
                  mountPath: /host/home/core/backup
              terminationMessagePolicy: File
          volumes:
            # HostPath volume for chroot
            - name: host
              hostPath:
                path: /
                type: Directory
            # PVC volume for storing backups
            - name: etcd-backup-volume
              persistentVolumeClaim:
                claimName: etcd-backup-pvc
          dnsPolicy: ClusterFirst
          tolerations:
            - key: node-role.kubernetes.io/master
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5