---
kind: ServiceAccount
apiVersion: v1
metadata: 
  name: cronjob-etcd-bkp-sa
  namespace: etcd-bkp
  labels:
    app: cronjob-etcd-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-etcd-bkp-cr
rules:
- apiGroups: [""]
  resources:
    -  "nodes"
  verbs: ["get","list"]
- apiGroups: [""]
  resources:
    - "pods"
    - "pods/log"
  verbs: ["get","list","create","delete","watch"]
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  resourceNames: ["privileged"]
  verbs: ["use"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  cronjob-etcd-bkp-crb
  labels:
    app: cronjob-etcd-backup
subjects:
  - kind: ServiceAccount
    name: cronjob-etcd-bkp-sa
    namespace: etcd-bkp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cronjob-etcd-bkp-cr