apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-backup-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  capacity:
    storage: 10Gi
  claimRef:
    name: etcd-backup-pvc
    namespace: etcd-backup
  nfs:
    server: 172.20.80.86
    path: /mnt/NFS/etcd-backup-elbisim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-backup-pvc
spec:
  volumeName: etcd-backup-pv
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi